"""Splits the live site's vector logo (baynes.co.uk/__shared_assets/header/baynes-logo.svg) into its three parts so
the page can recompose them: the wheat wreath with SINCE 1954, the BAYNE'S wordmark (cream letters on a maroon
drop shadow) and THE FAMILY BAKERS. Writes lib/logo.ts."""
import json, re, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
svg = (root / "public/brand/baynes-logo.svg").read_text()
parts = {"emblem": [], "shadow": [], "word": [], "tagline": []}
for m in re.finditer(r'<(path|polygon)\s+class="(st\d)"\s+(d|points)="([^"]+)"', svg):
    tag, cls, attr, val = m.groups()
    d = val if tag == "path" else "M" + " L".join(val.split()) + "Z"
    x = float(re.findall(r"-?\d+\.?\d*", val)[0])
    if cls == "st2": parts["shadow"].append(d)
    elif cls == "st3": parts["word"].append(d)
    elif cls == "st1": parts["emblem" if x < 250 else "tagline"].append(d)
# Rectangles (the I of FAMILY) become paths too; the full-size red field is the badge and is skipped.
for m in re.finditer(r'<rect\s+x="([\d.]+)"\s+y="([\d.]+)"\s+class="(st\d)"\s+width="([\d.]+)"\s+height="([\d.]+)"', svg):
    x, y, cls, w, h = m.groups()
    if cls == "st0": continue
    x, y, w, h = map(float, (x, y, w, h))
    d = f"M{x},{y}h{w}v{h}h{-w}Z"
    parts["tagline" if x > 600 else "emblem" if cls == "st1" else "word" if cls == "st3" else "shadow"].append(d)
out = "// Generated by scripts/logo.py from the live vector logo (viewBox 0 0 891.7 106). Do not edit by hand.\n"
out += "export const logo = " + json.dumps({k: " ".join(v) for k, v in parts.items()}) + " as const;\n"
out += "// Bounding boxes in the source viewBox: emblem 109 11 72 85, wordmark 259 22 302 59, tagline 613 46 225 14.\n"
(root / "lib/logo.ts").write_text(out)
print({k: len(v) for k, v in parts.items()})
